FakeHumans/Models/Human.cs
namespace FakeHumans.Models;

public class Human
{
    public required string FullName { get; set; }
    public required DateOnly DOB { get; set; }
    public required string Sex { get; set; }
    public required string Country { get; set; }
    public required string CIT { get; set; } 
    public required int Height { get; set; }
    public required string EyesColor { get; set; }
}

FakeHumans/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace FakeHumans.Controllers;

public class HomeController : Controller
{
    public IActionResult Index() => View();
}

FakeHumans/Controllers/NationsController.cs
using FakeHumans.Other;
using Microsoft.AspNetCore.Mvc;

namespace FakeHumans.Controllers;

public class NationsController : Controller
{
    public IActionResult Russians() => View(HumanContainer.Russians);
    public IActionResult Germans() => View(HumanContainer.Germans);
    public IActionResult Americans() => View(HumanContainer.Americans);
    public IActionResult Italians() => View(HumanContainer.Italians);
}

FakeHumans/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<p id="index-p">This website demonstrates a randomly <br> created human of each nation.</p>

FakeHumans/Views/Nations/Americans.cshtml
@model IEnumerable<FakeHumans.Models.Human>

@{
    ViewBag.Title = "Americans";
}

@foreach (FakeHumans.Models.Human human in Model)
{
    await Html.RenderPartialAsync("~/Views/Shared/_Card.cshtml", human);
}

FakeHumans/Views/Nations/Germans.cshtml
@model IEnumerable<FakeHumans.Models.Human>

@{
    ViewBag.Title = "Germans";
}

@foreach (FakeHumans.Models.Human human in Model)
{
    await Html.RenderPartialAsync("~/Views/Shared/_Card.cshtml", human);
}

FakeHumans/Views/Nations/Italians.cshtml
@model IEnumerable<FakeHumans.Models.Human>

@{
    ViewBag.Title = "Italians";
}

@foreach (FakeHumans.Models.Human human in Model)
{
    await Html.RenderPartialAsync("~/Views/Shared/_Card.cshtml", human);
}

FakeHumans/Views/Nations/Russians.cshtml
@model IEnumerable<FakeHumans.Models.Human> 

@{
    ViewBag.Title = "Russians";
}

@foreach (FakeHumans.Models.Human human in Model)
{
    await Html.RenderPartialAsync("~/Views/Shared/_Card.cshtml", human);
} 

FakeHumans/Views/Shared/_Card.cshtml
@model FakeHumans.Models.Human

<link rel="stylesheet" href="~/FakeHumans.styles.css" />
<div class='card'>
    <div id='image-wrapper'>
        <img src="~/img/dummy.jpg" alt="human_dummy">
    </div>
    <div id='content-wrapper'>
        <div class='row'>
            <p class='title'>FULL NAME</p>
            <p class='data'>@Model.FullName</p>
        </div>
        <div class='row'>
            <p class='title'>DOB</p>
            <p class='data'>@Model.DOB</p>
        </div>
        <div class='row'>
            <p class='title'>SEX</p>
            <p class='data'>@Model.Sex</p>
        </div>
        <div class='row'>
            <p class='title'>COUNTRY</p>
            <p class='data'>@Model.Country</p>
        </div>
        <div class='row'>
            <p class='title'>CIT</p>
            <p class='data'>@Model.CIT</p>
        </div>
        <div class='row'>
            <p class='title'>HEIGHT</p>
            <p class='data'>@Model.Height</p>
        </div>
        <div class='row'>
            <p class='title'>EYES COLOR</p>
            <p class='data'>@Model.EyesColor</p>
        </div>
    </div>
</div> 

FakeHumans/Views/Shared/_Footer.cshtml
<link rel="stylesheet" href="~/FakeHumans.styles.css" />
<div id="footer-wrapper">
    <div>
        <p>
            This is a fake website.<br/>
            All coincidences are random.<br/>
            No actual person or event was depicted.<br/>
        </p>
    </div>
    <div>
        <p>2024</p>
    </div>
</div>

FakeHumans/Views/Shared/_Header.cshtml
<link rel="stylesheet" href="~/FakeHumans.styles.css"/>
<div id="header-wrapper">
    <div id="header-logotype">
        <a href="@Url.Action("Index", "Home")">FakeHumans</a>
    </div>
    <div id="header-menu">
        <div class="header-menu-item">
            <a href="@Url.Action("Russians", "Nations")">Russians</a>
        </div>
        <div class="header-menu-item">
            <a href="@Url.Action("Germans", "Nations")">Germans</a>
        </div>
        <div class="header-menu-item">
            <a href="@Url.Action("Americans", "Nations")">Americans</a>
         </div>
        <div class="header-menu-item">
            <a href="@Url.Action("Italians", "Nations")">Italians</a>
        </div>
    </div>
</div>

FakeHumans/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>FakeHumans | @ViewBag.Title</title>
    <link href="~/css/main.css" rel="stylesheet"/>
</head>
<body>
    @await Html.PartialAsync("~/Views/Shared/_Header.cshtml")
    <div id="content">
        @RenderBody()
    </div>
    @await Html.PartialAsync("~/Views/Shared/_Footer.cshtml")
</body>
</html>